package com.gigaspaces.storm.googleanalytics.bolt.generic;

import backtype.storm.tuple.Tuple;
import org.apache.log4j.Logger;
import com.gigaspaces.storm.googleanalytics.tools.*;

/**
 * This bolt merges incoming {@link Rankings}.
 * <p/>
 * It can be used to merge intermediate rankings generated by {@link com.gigaspaces.storm.googleanalytics.bolt.generic.IntermediateRankingsBolt} into a final,
 * consolidated ranking. To do so, configure this bolt with a globalGrouping on {@link com.gigaspaces.storm.googleanalytics.bolt.generic.IntermediateRankingsBolt}.
 */
public class TotalRankingsBolt extends AbstractRankerBolt {

  private static final long serialVersionUID = -8447525895532302198L;
  private static final Logger LOG = Logger.getLogger(TotalRankingsBolt.class);

  public TotalRankingsBolt(int topN, int emitFrequencyInSeconds) {
    super(topN, emitFrequencyInSeconds);
  }

  @Override
  protected void updateRankingsWithTuple(Tuple tuple) {
    Rankings rankingsToBeMerged = (Rankings) tuple.getValue(0);
    super.getRankings().updateWith(rankingsToBeMerged);
    super.getRankings().pruneZeroCounts();
  }

  @Override
  protected Logger getLogger() {
    return LOG;
  }

}
